%:- set_global_compiler_options([singleton_warnings_off]).
%% load lexicon
:- ensure_loaded('lexicon/clex').
:- ensure_loaded('lexicon/clex_lexicon').
:- ensure_loaded('lexicon/lexicon_interface').
:- ensure_loaded('lexicon/functionwords').
:- ensure_loaded('lexicon/chars').
:- ensure_loaded('lexicon/illegalwords').
:- ensure_loaded('lexicon/is_in_lexicon').
:- ensure_loaded('lexicon/spellcheck').
:- ensure_loaded('logger/error_logger').
:- ensure_loaded('utils/drs_ops').
:- ensure_loaded('utils/drs_reverse').
:- ensure_loaded('utils/ace_niceace').
:- ensure_loaded('utils/drs_to_fol_to_prenex').
:- ensure_loaded('utils/drs_to_ergo').
:- ensure_loaded('utils/drs_to_cnf').
:- ensure_loaded('utils/drs_to_xml').
:- ensure_loaded('utils/drs_to_query').
:- ensure_loaded('utils/reform_predicate').
:- ensure_loaded('utils/util_phrase_extraction').
:- ensure_loaded('parser/tokenizer').
:- ensure_loaded('parser/tokens_to_sentences').
:- ensure_loaded('parser/refres').
:- ensure_loaded('parser/sentence_failure').
:- ensure_loaded('parser/grammar_words').
:- ensure_loaded('parser/ape_utils').
:- ensure_loaded('parser/grammar_functionwords').
:- ensure_loaded('parser/grammar_contentwords').
:- ensure_loaded('parser/grammar').
:- ensure_loaded('parser/ace_to_drs').
:- ensure_loaded('parser/defres').
:- ensure_loaded('semanticparsing/valid_fe_val_list.pl').
:- ensure_loaded('semanticparsing/construct_pattern.pl').
:- ensure_loaded('semanticparsing/serialize_pattern.pl').
:- ensure_loaded('semanticparsing/annotate_sentence.pl').
:- ensure_loaded('semanticparsing/fe_extractor.pl').
:- ensure_loaded('semanticparsing/data/lfe.pl').
:- ensure_loaded('semanticparsing/data/lvp.pl').
:- ensure_loaded('semanticparsing/data/sentence_annotation.pl').
:- ensure_loaded('semanticparsing/drs_to_babelfy_input.pl').
:- ensure_loaded('semanticparsing/parse_and_serialize.pl').
:- ensure_loaded('semanticparsing/extract_frame_and_serialize.pl').
:- ensure_loaded('query/qparse.pl').
:- ensure_loaded('tmp/serialized_drs_fact.pl').
:- ensure_loaded('query/qframe_extraction.pl').
